name: SwiftDemo

options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "15.0"

packages:
  TelemetryKit:
    path: ../..

targets:
  SwiftDemo:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources/PrivacyInfo.xcprivacy
        buildPhase: resources
    dependencies:
      - package: TelemetryKit
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.telemetrykit.samples.swift
        PRODUCT_NAME: SwiftDemo
        INFOPLIST_FILE: Resources/Info.plist
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"

  SwiftDemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - ../UITests
    dependencies:
      - target: SwiftDemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.telemetrykit.samples.swift.uitests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
schemes:
  SwiftDemo:
    build:
      targets:
        SwiftDemo: all
    run:
      config: Debug
    test:
      targets:
        - SwiftDemoUITests
    archive:
      config: Release
